### ISSUE TITLE
Is there a way to clip the shimmer to the child below?

### ISSUE THREAD

**Issue by dheerajbred** [101Loop/Skeleton-Text#2]
Not an issue.
Is there a way to clip the shimmer to the child below? The shimmer is overflowing. Like a Cupertinobutton with shimmer

**Comment by imlegend19** [comment]
Hey, thanks for opening an issue! You can try adding max-width to the parent using MediaQuery.
```python
MediaQuery.of(context).size.width
```
Or try wrapping the parent with `Expanded`. Let me know if this works.

**Comment by dheerajbred** [comment]
https://user-images.githubusercontent.com/46578244/104626237-a90ce600-56bb-11eb-9b98-3ff7b9aa7953.mp4

Hey, thanks for the reply.
I am referring to the overflow of the shimmer. The shimmer overflows child widgets with different boundary like rounded cornered button or a variable shape or an icon perhaps.

**Comment by imlegend19** [comment]
This issue has been fixed in #1. Thus, closing!
