### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [101Loop/Skeleton-Text#3]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:skeleton_text`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by imlegend19** [comment]
Hi @IchordeDionysos, thanks for opening an issue. 

Will add support for `null safety` in the next version!

**Comment by IchordeDionysos** [comment]
@imlegend19 thanks, really appreciate it 👍

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by StanevPrime** [comment]
Could you please revise this PR :)
https://github.com/101Loop/Skeleton-Text/pull/4
